language: python

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - NUMPY_VERSION=1.8
        - ASTROPY_VERSION=stable
        - CONDA_DEPENDENCIES='matplotlib pyparsing'

    matrix:
        - SETUP_CMD='egg_info'
        - SETUP_CMD='test'

matrix:
    include:

        # Do a coverage test in Python 2.
        - python: 2.7
          env: SETUP_CMD='test --coverage'

        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        - python: 2.7
          env: SETUP_CMD='build_sphinx'
               PIP_DEPENDENCIES='sphinx_rtd_theme wcsaxes'

        # Try Astropy development version
        - python: 2.7
          env: ASTROPY_VERSION=development SETUP_CMD='test'
        - python: 3.3
          env: ASTROPY_VERSION=development SETUP_CMD='test'

        # Try older numpy versions
        - python: 2.7
          env: NUMPY_VERSION=1.7 SETUP_CMD='test'
        - python: 2.7
          env: NUMPY_VERSION=1.6 SETUP_CMD='test'
        - python: 2.7
          env: NUMPY_VERSION=1.5 SETUP_CMD='test'

before_install:
    # Make sure that interactive matplotlib backends work
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
   - python setup.py $SETUP_CMD

after_success:
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then
          coveralls --rcfile='pyregion/tests/coveragerc';
      fi
